name: 'GLAC - GitHub labels as code'
author: "jop-software Inh. Johannes Przymusinski"
description: 'Store your labels as code in the repository'
branding:
  icon: "bookmark"
  color: "green"
inputs:
  token:
    description: >
      Personal access token (PAT) used to update the labels via the API.
      Usually (any per default) `github.token`
    default: ${{ github.token }}
  file:
    description: >
      The JSON file you store your label information in.
    default: './.github/labels.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
