name: 'GLAC - GitHub labels as code'
description: 'Store your labels as code in the repository'
inputs:
  token:
    description: >
      Personal access token (PAT) used to update the labels via the API.
      Usually (any per default) `github.token`
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
