on: [push]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    name: "Sync issue labels"
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'jop-software/github-labels-as-code-action@main'
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
